"""フェーズ2：決まった部分の Go 変換（AI無し・毎回同じ結果）。

  entity → struct ＋ 箱（goroutine 1つ＋受信 channel。同じ箱への書き換えは1つずつ）
  flow   → 遷移表 ＋ Move（-> の通りにしか動けない）＋ on conflict の勝者判定
  list   → フィルタ関数（where は全部 and、sort by は昇順）
  match  → 表引き関数（otherwise が default）
  rule   → 出来事ごとのハンドラ（時間／user says／データ）
  action → interface だけ（中身は空）＋ example からテスト
  how    → limit / on failure retry を適用するラッパー

変換できない書き方（仕様に無い／決まっていない）は推測せず CodegenError で止める。
出力は spec の内容だけから決まる（時刻・乱数・辞書の順序に依存しない）。
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field

from .checker import classify_when, parse_move
from .parser import (
    Node, Spec, entity_fields, flow_conflicts, flow_states, flow_target,
    flow_transitions, one_of_values,
)


class CodegenError(Exception):
    def __init__(self, line: int, message: str):
        super().__init__(f"L{line}: {message}")
        self.line = line


# ---------------------------------------------------------------------------
# 名前と型
# ---------------------------------------------------------------------------

def go_name(name: str) -> str:
    """owner → Owner, due_soon → DueSoon, Application → Application"""
    parts = re.split(r"[_\-\s]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def go_lower(name: str) -> str:
    n = go_name(name)
    return n[:1].lower() + n[1:]


BUILTIN_TYPES = {
    "text": "string",
    "number": "float64",
    "datetime": "time.Time",
    "duration": "time.Duration",
}

_DURATION = re.compile(r"^(\d+)\s+(seconds?|minutes?|hours?|days?|weeks?)$")


def go_duration(text: str) -> str:
    """`3 days` → `3 * 24 * time.Hour`"""
    m = _DURATION.match(text.strip())
    if not m:
        raise ValueError(text)
    n, unit = m.group(1), m.group(2).rstrip("s")
    return {
        "second": f"{n} * time.Second",
        "minute": f"{n} * time.Minute",
        "hour": f"{n} * time.Hour",
        "day": f"{n} * 24 * time.Hour",
        "week": f"{n} * 7 * 24 * time.Hour",
    }[unit]


@dataclass
class Field:
    name: str
    spec_type: str
    go_type: str
    line: int
    one_of: list[str] | None = None
    ref: str | None = None


@dataclass
class Model:
    """spec から codegen に必要なものだけ取り出した形。"""
    entities: dict[str, list[Field]] = field(default_factory=dict)
    entity_order: list[str] = field(default_factory=list)
    opaque_types: list[str] = field(default_factory=list)  # Message など未定義の型名


def go_type_of(spec_type: str, model: Model, line: int) -> Field:
    t = spec_type.strip()
    if t in BUILTIN_TYPES:
        return Field("", t, BUILTIN_TYPES[t], line)
    vals = one_of_values(t)
    if vals is not None:
        return Field("", t, "string", line, one_of=vals)
    if t.startswith("ref "):
        target = t[4:].strip()
        return Field("", t, "string", line, ref=target)
    if t.startswith("many "):
        target = t[5:].strip()
        return Field("", t, "[]string", line, ref=target)
    if t in model.entities:
        return Field("", t, go_name(t), line)
    if re.fullmatch(r"[A-Z]\w*", t):
        # 未定義の型名（connect が持ってくる Message など）。QUESTIONS Q3
        if t not in model.opaque_types:
            model.opaque_types.append(t)
        return Field("", t, go_name(t), line)
    raise CodegenError(line, f"型が分かりません: '{spec_type}'")


def build_model(spec: Spec) -> Model:
    model = Model()
    for e in spec.decls_of("entity"):
        model.entity_order.append(e.name)
        model.entities[e.name] = []
    for e in spec.decls_of("entity"):
        fields = []
        for name, typ, line in entity_fields(e):
            f = go_type_of(typ, model, line)
            f.name = name
            fields.append(f)
        model.entities[e.name] = fields
    return model


# ---------------------------------------------------------------------------
# 出力の道具
# ---------------------------------------------------------------------------

class Out:
    """Go ファイル1つ分。import は本文で使っている標準パッケージから自動で決める。"""

    STD = ("context", "errors", "fmt", "regexp", "sort", "strings", "sync", "testing", "time")

    def __init__(self, package: str, imports: list[str] | None = None):
        self.lines: list[str] = []
        self.package = package

    def w(self, line: str = ""):
        self.lines.append(line)

    def text(self) -> str:
        body = "\n".join(self.lines)
        imports = sorted(p for p in self.STD if re.search(rf"\b{p}\.", body))
        head = [
            "// Code generated by nameless-lang codegen. DO NOT EDIT.",
            "// 仕様(.spec)から AI 無しで決まった変換をしたもの。同じ仕様からは毎回同じ結果になる。",
            "",
            f"package {self.package}",
            "",
        ]
        if imports:
            head.append("import (")
            for imp in imports:
                head.append(f'\t"{imp}"')
            head.append(")")
            head.append("")
        return gofmt("\n".join(head) + "\n" + body.rstrip("\n") + "\n")


def gofmt(text: str) -> str:
    """gofmt があれば整形する（決定的）。無ければそのまま。"""
    import shutil
    import subprocess
    exe = shutil.which("gofmt")
    if not exe:
        return text
    r = subprocess.run([exe], input=text, capture_output=True, text=True)
    if r.returncode != 0:
        raise CodegenError(0, "gofmt が通りません:\n" + r.stderr + "\n" + text)
    return r.stdout


def q(s: str) -> str:
    """Go の文字列リテラル"""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# ---------------------------------------------------------------------------
# entity → struct + 箱
# ---------------------------------------------------------------------------

def gen_entities(spec: Spec, model: Model, package: str) -> str:
    o = Out(package)
    o.w("// ---- 型 ----")
    o.w()
    for t in model.opaque_types:
        o.w(f"// {t} は仕様の中で定義されていない型（connect が持ってくる想定）。text として扱う。QUESTIONS.md Q3")
        o.w(f"type {go_name(t)} string")
        o.w()
    for ename in model.entity_order:
        E = go_name(ename)
        o.w(f"// {E} — entity {ename}")
        o.w(f"type {E} struct {{")
        o.w(f"\tID string")
        for f in model.entities[ename]:
            comment = f"// {f.spec_type}"
            o.w(f"\t{go_name(f.name)} {f.go_type} {comment}")
        o.w("}")
        o.w()
        for f in model.entities[ename]:
            if f.one_of:
                o.w(f"// {E}.{go_name(f.name)} の取りうる値")
                o.w("const (")
                for v in f.one_of:
                    o.w(f"\t{E}{go_name(f.name)}{go_name(v)} = {q(v)}")
                o.w(")")
                o.w()
        o.w(f"// {E}Box — entity {ename} の1件＝1つの箱。")
        o.w("// 箱への書き換えは受信 channel を1つの goroutine が順に処理する（同じ箱の中は1つずつ）。")
        o.w(f"type {E}Box struct {{")
        o.w(f"\tinbox chan {go_lower(ename)}Msg")
        o.w(f"\tstate {E}")
        o.w(f"\tprev  {E} // 直前の状態（on conflict の判定に使う）")
        o.w("}")
        o.w()
        o.w(f"type {go_lower(ename)}Msg struct {{")
        o.w(f"\tapply func(cur *{E}, prev *{E}) error // prev は状態を進めるときに apply が書き換える")
        o.w(f"\tread  func(cur {E})")
        o.w("\tdone  chan error")
        o.w("}")
        o.w()
        o.w(f"// New{E}Box は箱を作って goroutine を起動する。")
        o.w(f"func New{E}Box(v {E}) *{E}Box {{")
        o.w(f"\tb := &{E}Box{{inbox: make(chan {go_lower(ename)}Msg), state: v, prev: v}}")
        o.w("\tgo b.loop()")
        o.w("\treturn b")
        o.w("}")
        o.w()
        o.w(f"func (b *{E}Box) loop() {{")
        o.w("\tfor m := range b.inbox {")
        o.w("\t\tif m.read != nil {")
        o.w("\t\t\tm.read(b.state)")
        o.w("\t\t\tm.done <- nil")
        o.w("\t\t\tcontinue")
        o.w("\t\t}")
        o.w("\t\tnext := b.state")
        o.w("\t\tprev := b.prev")
        o.w("\t\terr := m.apply(&next, &prev)")
        o.w("\t\tif err == nil {")
        o.w("\t\t\tb.state = next")
        o.w("\t\t\tb.prev = prev")
        o.w("\t\t}")
        o.w("\t\tm.done <- err")
        o.w("\t}")
        o.w("}")
        o.w()
        o.w(f"// Update は箱の中身を書き換える。順番に1つずつ処理される。")
        o.w(f"func (b *{E}Box) Update(fn func(cur *{E}, prev *{E}) error) error {{")
        o.w(f"\tm := {go_lower(ename)}Msg{{apply: fn, done: make(chan error, 1)}}")
        o.w("\tb.inbox <- m")
        o.w("\treturn <-m.done")
        o.w("}")
        o.w()
        o.w(f"// Get は箱の中身のコピーを返す。")
        o.w(f"func (b *{E}Box) Get() {E} {{")
        o.w(f"\tvar out {E}")
        o.w(f"\tm := {go_lower(ename)}Msg{{read: func(cur {E}) {{ out = cur }}, done: make(chan error, 1)}}")
        o.w("\tb.inbox <- m")
        o.w("\t<-m.done")
        o.w("\treturn out")
        o.w("}")
        o.w()
        o.w(f"// Close は箱の goroutine を止める。")
        o.w(f"func (b *{E}Box) Close() {{ close(b.inbox) }}")
        o.w()

    # Store: 箱の集まり。箱をまたぐ処理は並列（ルールは箱ごとに goroutine で走る）
    o.w("// Store — 箱の集まり。箱をまたぐ処理は並列に走る（EachParallel）。")
    o.w("type Store struct {")
    o.w("\tmu sync.RWMutex")
    for ename in model.entity_order:
        o.w(f"\t{go_name(ename)}s []*{go_name(ename)}Box")
    o.w("}")
    o.w()
    o.w("func NewStore() *Store { return &Store{} }")
    o.w()
    for ename in model.entity_order:
        E = go_name(ename)
        o.w(f"// Add{E} は新しい箱を作って Store に入れる。")
        o.w(f"func (s *Store) Add{E}(v {E}) *{E}Box {{")
        o.w(f"\tb := New{E}Box(v)")
        o.w("\ts.mu.Lock()")
        o.w(f"\ts.{E}s = append(s.{E}s, b)")
        o.w("\ts.mu.Unlock()")
        o.w("\treturn b")
        o.w("}")
        o.w()
        o.w(f"// All{E}s は今の中身のスナップショット（読むだけ）。")
        o.w(f"func (s *Store) All{E}s() []{E} {{")
        o.w("\ts.mu.RLock()")
        o.w(f"\tboxes := append([]*{E}Box(nil), s.{E}s...)")
        o.w("\ts.mu.RUnlock()")
        o.w(f"\tout := make([]{E}, 0, len(boxes))")
        o.w("\tfor _, b := range boxes {")
        o.w("\t\tout = append(out, b.Get())")
        o.w("\t}")
        o.w("\treturn out")
        o.w("}")
        o.w()
        o.w(f"// Each{E}Parallel は箱ごとに並列で fn を走らせ、全部終わるのを待つ。箱をまたぐ処理は並列が標準。")
        o.w(f"func (s *Store) Each{E}Parallel(fn func(b *{E}Box)) {{")
        o.w("\ts.mu.RLock()")
        o.w(f"\tboxes := append([]*{E}Box(nil), s.{E}s...)")
        o.w("\ts.mu.RUnlock()")
        o.w("\tvar wg sync.WaitGroup")
        o.w("\tfor _, b := range boxes {")
        o.w("\t\twg.Add(1)")
        o.w(f"\t\tgo func(b *{E}Box) {{")
        o.w("\t\t\tdefer wg.Done()")
        o.w("\t\t\tfn(b)")
        o.w("\t\t}(b)")
        o.w("\t}")
        o.w("\twg.Wait()")
        o.w("}")
        o.w()
        o.w(f"// Close は全部の箱を止める。")
    o.w("func (s *Store) Close() {")
    o.w("\ts.mu.Lock()")
    o.w("\tdefer s.mu.Unlock()")
    for ename in model.entity_order:
        E = go_name(ename)
        o.w(f"\tfor _, b := range s.{E}s {{")
        o.w("\t\tb.Close()")
        o.w("\t}")
    o.w("}")
    return o.text()


# ---------------------------------------------------------------------------
# flow → 遷移表 + Move + on conflict
# ---------------------------------------------------------------------------

def gen_flows(spec: Spec, model: Model, package: str) -> str:
    o = Out(package)
    for fl in spec.decls_of("flow"):
        ename, fname = flow_target(fl)
        if ename not in model.entities:
            raise CodegenError(fl.line, f"flow {fl.name}: entity {ename} がありません")
        E, F = go_name(ename), go_name(fname)
        states = flow_states(fl)
        edges = flow_transitions(fl)
        conflicts = flow_conflicts(fl)
        o.w(f"// ---- flow {fl.name} ----")
        o.w(f"// {' / '.join(spec.lines[c.line - 1].strip() for c in fl.children)}")
        o.w()
        o.w(f"// {E}{F}Transitions — -> の通りにしか動けない。")
        o.w(f"var {E}{F}Transitions = map[string][]string{{")
        for s in states:
            dsts = [d for (src, d) in edges if src == s]
            items = ", ".join(q(d) for d in dsts)
            o.w(f"\t{q(s)}: {{{items}}},")
        o.w("}")
        o.w()
        o.w(f"// {E}{F}WinsOver — on conflict の勝者。[勝者][敗者] = true")
        o.w(f"var {E}{F}WinsOver = map[string]map[string]bool{{")
        winners: dict[str, list[str]] = {}
        for w, l in conflicts:
            winners.setdefault(w, []).append(l)
        for w in sorted(winners):
            items = ", ".join(f"{q(l)}: true" for l in sorted(winners[w]))
            o.w(f"\t{q(w)}: {{{items}}},")
        o.w("}")
        o.w()
        o.w(f"func {go_lower(ename)}{F}CanMove(from, to string) bool {{")
        o.w(f"\tfor _, d := range {E}{F}Transitions[from] {{")
        o.w("\t\tif d == to {")
        o.w("\t\t\treturn true")
        o.w("\t\t}")
        o.w("\t}")
        o.w("\treturn false")
        o.w("}")
        o.w()
        o.w(f"// Move{F} は {ename}.{fname} を to へ動かす。flow で管理する項目は move でしか変えられない（set 禁止）。")
        o.w("//")
        o.w("// on conflict: 同じ元の状態から分岐した先に、矛盾する move が続けて届いたとき、")
        o.w("//   - 今の状態が to に負けるなら to で上書きする")
        o.w("//   - 今の状態が to に勝つなら何もしない（エラーにもしない）")
        o.w(f"func (b *{E}Box) Move{F}(to string) error {{")
        o.w(f"\treturn b.Update(func(cur *{E}, prev *{E}) error {{")
        o.w(f"\t\tif cur.{F} == to {{")
        o.w("\t\t\treturn nil")
        o.w("\t\t}")
        o.w(f"\t\tif {go_lower(ename)}{F}CanMove(cur.{F}, to) {{")
        o.w("\t\t\t*prev = *cur")
        o.w(f"\t\t\tcur.{F} = to")
        o.w("\t\t\treturn nil")
        o.w("\t\t}")
        o.w(f"\t\t// 矛盾する move: 直前の状態から cur.{F} と to の両方へ行ける")
        o.w(f"\t\tif {go_lower(ename)}{F}CanMove(prev.{F}, to) && {go_lower(ename)}{F}CanMove(prev.{F}, cur.{F}) {{")
        o.w(f"\t\t\tif {E}{F}WinsOver[to][cur.{F}] {{")
        o.w(f"\t\t\t\tcur.{F} = to // prev はそのまま（同じ分岐点からの上書き）")
        o.w("\t\t\t\treturn nil")
        o.w("\t\t\t}")
        o.w(f"\t\t\tif {E}{F}WinsOver[cur.{F}][to] {{")
        o.w("\t\t\t\treturn nil")
        o.w("\t\t\t}")
        o.w("\t\t}")
        o.w(f'\t\treturn fmt.Errorf("{ename}.{fname}: %s から %s へは動けません", cur.{F}, to)')
        o.w("\t})")
        o.w("}")
        o.w()
    return o.text()


# ---------------------------------------------------------------------------
# list → フィルタ関数
# ---------------------------------------------------------------------------

_WHERE_IS = re.compile(r"^(\w+) is (\{?\w+\}?|\"[^\"]*\")$")
_WHERE_WITHIN = re.compile(r"^(\w+) within (\d+ \w+)$")


def where_to_go(cond: str, fields: dict[str, Field], line: int, var: str = "x") -> tuple[str, set[str]]:
    """where の1行を Go の条件式にする。戻り: (式, 必要な import)"""
    m = _WHERE_IS.match(cond.strip())
    if m:
        fname, value = m.group(1), m.group(2)
        if fname not in fields:
            raise CodegenError(line, f"where: 項目 {fname} がありません")
        f = fields[fname]
        if value.startswith("{") and value.endswith("}"):
            return f"{var}.{go_name(fname)} == {go_lower(value[1:-1])}", set()
        if value.startswith('"'):
            return f"{var}.{go_name(fname)} == {value}", set()
        if f.one_of is not None and value not in f.one_of:
            raise CodegenError(line, f"where: {fname} に {value} という値はありません（{', '.join(f.one_of)}）")
        return f"{var}.{go_name(fname)} == {q(value)}", set()
    m = _WHERE_WITHIN.match(cond.strip())
    if m:
        fname, dur = m.group(1), m.group(2)
        if fname not in fields or fields[fname].go_type != "time.Time":
            raise CodegenError(line, f"where: within は datetime の項目にだけ使えます: '{cond}'")
        try:
            d = go_duration(dur)
        except ValueError:
            raise CodegenError(line, f"where: 期間が読めません: '{dur}'")
        # now <= 値 <= 期限。days / weeks は暦日で数える（仕様の example がそれを前提にしている。QUESTIONS.md Q19）
        n, unit = dur.split()
        if unit.rstrip("s") in ("day", "week"):
            days = int(n) * (7 if unit.startswith("week") else 1)
            end = f"endOfDay(now.AddDate(0, 0, {days}))"
        else:
            end = f"now.Add({d})"
        return f"!{var}.{go_name(fname)}.Before(now) && !{var}.{go_name(fname)}.After({end})", {"time"}
    raise CodegenError(line, f"where の書き方が分かりません（決まっているのは `項目 is 値` と `項目 within 期間`）: '{cond}'")


def list_source_entity(spec: Spec, lst: Node) -> str:
    """list の元をたどって entity 名にする。"""
    seen = set()
    cur = lst
    while True:
        fr = cur.child("from")
        if fr is None:
            raise CodegenError(cur.line, f"list {cur.name}: from がありません")
        src = fr.text.strip()
        if src in seen:
            raise CodegenError(cur.line, f"list {cur.name}: 循環参照")
        seen.add(src)
        nxt = spec.find("list", src)
        if nxt is None:
            return src
        cur = nxt


def gen_lists(spec: Spec, model: Model, package: str) -> str:
    imports = {"sort"}
    body: list[str] = []
    for lst in spec.decls_of("list"):
        ename = list_source_entity(spec, lst)
        if ename not in model.entities:
            raise CodegenError(lst.line, f"list {lst.name}: from の {ename} は entity ではありません")
        E = go_name(ename)
        fields = {f.name: f for f in model.entities[ename]}
        src = lst.child("from").text.strip()
        L = go_name(lst.name)
        body.append(f"// {L} — list {lst.name}")
        body.append(f"// {' / '.join(spec.lines[c.line - 1].strip() for c in lst.children)}")
        body.append(f"func {L}(all []{E}, now time.Time) []{E} {{")
        imports.add("time")
        if src in model.entities:
            body.append("\tsrc := all")
        else:
            body.append(f"\tsrc := {go_name(src)}(all, now)")
        body.append(f"\tout := make([]{E}, 0, len(src))")
        body.append("\tfor _, x := range src {")
        conds = []
        for w in lst.children_of("where"):
            expr, imps = where_to_go(w.text, fields, w.line)
            imports |= imps
            conds.append(expr)
        if conds:
            body.append(f"\t\tif !({' && '.join(f'({c})' for c in conds)}) {{")
            body.append("\t\t\tcontinue")
            body.append("\t\t}")
        body.append("\t\tout = append(out, x)")
        body.append("\t}")
        sb = lst.child("sort by")
        if sb is not None:
            key = sb.text.strip()
            if key not in fields:
                raise CodegenError(sb.line, f"sort by: 項目 {key} がありません")
            K = go_name(key)
            if fields[key].go_type == "time.Time":
                less = f"out[i].{K}.Before(out[j].{K})"
            else:
                less = f"out[i].{K} < out[j].{K}"
            body.append("\tsort.SliceStable(out, func(i, j int) bool { return " + less + " })")
        body.append("\treturn out")
        body.append("}")
        body.append("")
    if body:
        body.append("// endOfDay — その日の 23:59:59.999999999。within N days は暦日で数える。")
        body.append("func endOfDay(t time.Time) time.Time {")
        body.append("\ty, m, d := t.Date()")
        body.append("\treturn time.Date(y, m, d, 23, 59, 59, 999999999, t.Location())")
        body.append("}")
    o = Out(package)
    for l in body:
        o.w(l)
    return o.text()


# ---------------------------------------------------------------------------
# match → 表引き
# ---------------------------------------------------------------------------

def gen_matches(spec: Spec, model: Model, package: str) -> str:
    o = Out(package)
    for m in spec.decls_of("match"):
        words = m.text.split()
        if len(words) != 3 or words[1] != "to" or "." not in words[0]:
            raise CodegenError(m.line, f"match は `match 箱.項目 to 名前` で書きます: '{m.raw}'")
        ename, fname = words[0].split(".", 1)
        target = words[2]
        if ename not in model.entities:
            raise CodegenError(m.line, f"match: entity {ename} がありません")
        fields = {f.name: f for f in model.entities[ename]}
        if fname not in fields:
            raise CodegenError(m.line, f"match: 項目 {fname} がありません")
        F = go_name(ename) + go_name(fname) + "To" + go_name(target)
        o.w(f"// {F} — match {m.text}。結果は text 扱い（QUESTIONS.md Q6）")
        o.w(f"func {F}(v string) string {{")
        o.w("\tswitch v {")
        otherwise = None
        for arm in m.children:
            if arm.keyword == "otherwise":
                otherwise = arm.text.split("->", 1)[1].strip()
                continue
            if "->" not in arm.raw:
                raise CodegenError(arm.line, f"match の行は `値 -> 結果` で書きます: '{arm.raw}'")
            k, v = [s.strip() for s in arm.raw.split("->", 1)]
            if fields[fname].one_of is not None and k not in fields[fname].one_of:
                raise CodegenError(arm.line, f"match: {fname} に {k} という値はありません")
            o.w(f"\tcase {q(k)}:")
            o.w(f"\t\treturn {q(v)}")
        o.w("\tdefault:")
        o.w(f"\t\treturn {q(otherwise)}")
        o.w("\t}")
        o.w("}")
        o.w()
    return o.text()


# ---------------------------------------------------------------------------
# rule → 出来事ハンドラ
# ---------------------------------------------------------------------------

_SAYS = re.compile(r'^user says "(.*)"$')
_NOTIFY_EACH = re.compile(r"^notify user each of (\w+)$")
_NOTIFY_TEXT = re.compile(r'^notify user "(.*)"$')
_TIME_EVERY = re.compile(r"^every (\w+) at (\d{1,2}:\d{2})$")
_DATA = re.compile(r"^(\w+) (is created|moves to \w+|is removed)$")


def says_pattern_to_regexp(pattern: str) -> tuple[str, list[str]]:
    """`submitted {company}` → (`^submitted (?P<company>.+)$`, ["company"])"""
    names: list[str] = []
    out = "^"
    pos = 0
    for m in re.finditer(r"\{(\w+)\}", pattern):
        out += re.escape(pattern[pos:m.start()])
        out += f"(?P<{m.group(1)}>.+)"
        names.append(m.group(1))
        pos = m.end()
    out += re.escape(pattern[pos:]) + "$"
    return out, names


def gen_rules(spec: Spec, model: Model, package: str) -> str:
    imports = {"time"}
    body: list[str] = []
    body.append("// Effects — ルールが外に向かってやること。中身はアプリ側が用意する。")
    body.append("type Effects interface {")
    body.append("\t// Notify はユーザーに通知する。item は通知の対象（entity の値か文字列）。")
    body.append("\tNotify(rule string, item any)")
    body.append("}")
    body.append("")
    body.append("// Schedule — 時間の出来事。")
    body.append("type Schedule struct {")
    body.append("\tEvery string // day / monday / ...")
    body.append("\tAt    string // 21:00")
    body.append("}")
    body.append("")

    for r in spec.decls_of("rule"):
        R = go_name(r.name)
        when = r.child("when")
        do = r.child("do")
        because = r.child("because")
        if when is None or do is None:
            raise CodegenError(r.line, f"rule {r.name}: when と do が要ります")
        kind = classify_when(when.text)
        body.append(f"// ---- rule {r.name} ----")
        if because is not None:
            body.append(f"// because {because.text}")
        body.append(f"// when {when.text}")
        body.append(f"// do {do.text}")
        body.append("")

        # when の形ごとに関数の入口を決める
        params = ["s *Store", "fx Effects", "now time.Time"]
        extra_vars: list[str] = []
        if kind == "time":
            m = _TIME_EVERY.match(when.text.strip())
            if m:
                body.append(f"// {R}Schedule — いつ動かすか。")
                body.append(f"var {R}Schedule = Schedule{{Every: {q(m.group(1))}, At: {q(m.group(2))}}}")
                body.append("")
        elif kind == "user":
            m = _SAYS.match(when.text.strip())
            if m:
                rx, names = says_pattern_to_regexp(m.group(1))
                imports.add("regexp")
                body.append(f"var {go_lower(r.name)}Pattern = regexp.MustCompile({q(rx)})")
                body.append("")
                sig = ", ".join(f"{go_lower(n)} string" for n in names)
                body.append(f"// Match{R} — user says の文からルールの入力を取り出す。")
                body.append(f"func Match{R}(text string) ({sig + ', ' if sig else ''}ok bool) {{")
                body.append(f"\tm := {go_lower(r.name)}Pattern.FindStringSubmatch(text)")
                body.append("\tif m == nil {")
                body.append("\t\treturn")
                body.append("\t}")
                for i, n in enumerate(names):
                    body.append(f"\t{go_lower(n)} = m[{i + 1}]")
                body.append("\tok = true")
                body.append("\treturn")
                body.append("}")
                body.append("")
                extra_vars = names
                params += [f"{go_lower(n)} string" for n in names]
            else:
                # user does 〇〇: 入力は無し
                pass
        elif kind == "data":
            m = _DATA.match(when.text.strip())
            ename = m.group(1)
            if ename not in model.entities:
                raise CodegenError(when.line, f"rule {r.name}: {ename} は entity ではありません")
            params.append(f"target *{go_name(ename)}Box")
        elif kind == "external":
            raise CodegenError(when.line, f"rule {r.name}: connect からの出来事は △（設計は次回）なので変換できません: '{when.text}'")

        body.append(f"// Rule{R} — 出来事が起きたら呼ぶ。中で対象の箱ごとに並列に動く。")
        body.append(f"func Rule{R}({', '.join(params)}) error {{")
        body += _gen_do(spec, model, r, do, extra_vars)
        body.append("}")
        body.append("")

    o = Out(package)
    for l in body:
        o.w(l)
    return o.text()


def _gen_do(spec: Spec, model: Model, r: Node, do: Node, vars_: list[str]) -> list[str]:
    text = do.text.strip()
    lines: list[str] = []
    m = _NOTIFY_EACH.match(text)
    if m:
        lname = m.group(1)
        lst = spec.find("list", lname)
        if lst is None:
            raise CodegenError(do.line, f"rule {r.name}: list {lname} がありません")
        ename = list_source_entity(spec, lst)
        E = go_name(ename)
        lines.append(f"\tfor _, item := range {go_name(lname)}(s.All{E}s(), now) {{")
        lines.append(f"\t\tfx.Notify({q(r.name)}, item)")
        lines.append("\t}")
        lines.append("\treturn nil")
        return lines
    m = _NOTIFY_TEXT.match(text)
    if m:
        lines.append(f"\tfx.Notify({q(r.name)}, {q(m.group(1))})")
        lines.append("\treturn nil")
        return lines
    mv = parse_move(text)
    if mv:
        ename = mv["target"]
        if ename not in model.entities:
            raise CodegenError(do.line, f"rule {r.name}: {ename} は entity ではありません")
        E = go_name(ename)
        fields = {f.name: f for f in model.entities[ename]}
        flows = [f for f in spec.decls_of("flow") if flow_target(f)[0] == ename]
        state_fields = [f for f in fields.values() if f.one_of and mv["state"] in f.one_of]
        if not state_fields:
            raise CodegenError(do.line, f"rule {r.name}: {ename} に {mv['state']} という状態はありません")
        F = go_name(state_fields[0].name)
        if not any(flow_target(f)[1] == state_fields[0].name for f in flows):
            raise CodegenError(do.line, f"rule {r.name}: {ename}.{state_fields[0].name} に flow がありません（move は flow で管理する項目にだけ使えます）")
        cond, _ = where_to_go(mv["where"], fields, do.line, var="cur")
        lines.append("\tvar firstErr error")
        lines.append("\tvar mu sync.Mutex")
        lines.append(f"\ts.Each{E}Parallel(func(b *{E}Box) {{")
        lines.append("\t\tcur := b.Get()")
        lines.append(f"\t\tif !({cond}) {{")
        lines.append("\t\t\treturn")
        lines.append("\t\t}")
        lines.append(f"\t\tif err := b.Move{F}({q(mv['state'])}); err != nil {{")
        lines.append("\t\t\tmu.Lock()")
        lines.append("\t\t\tif firstErr == nil {")
        lines.append("\t\t\t\tfirstErr = err")
        lines.append("\t\t\t}")
        lines.append("\t\t\tmu.Unlock()")
        lines.append("\t\t}")
        lines.append("\t})")
        lines.append("\treturn firstErr")
        return lines
    raise CodegenError(do.line, f"rule {r.name}: do の書き方が分かりません（決まっているのは notify user each of 〇〇 / notify user \"...\" / move 箱 where 条件 to 状態）: '{text}'")



# ---------------------------------------------------------------------------
# action → interface + how ラッパー + example テスト
# ---------------------------------------------------------------------------

_IO = re.compile(r"^(\w+):\s*(.+)$")
_HOW_LIMIT = re.compile(r"^limit (\d+ \w+)$")
_HOW_RETRY = re.compile(r"^on failure retry (\d+) times?$")


@dataclass
class ActionSig:
    name: str
    in_name: str
    in_type: Field
    out_name: str
    out_type: Field
    examples: list[tuple[str, str, int]]
    else_: str
    nevers: list[str]
    by: str
    limit: str | None
    retry: int | None
    how_unknown: list[str]


def read_action(a: Node, model: Model) -> ActionSig:
    inp, out = a.child("input"), a.child("output")
    if inp is None or out is None:
        raise CodegenError(a.line, f"action {a.name}: input と output が要ります")
    mi = _IO.match(inp.text.strip())
    if not mi:
        raise CodegenError(inp.line, f"input は `名前: 型` で書きます: '{inp.text}'")
    mo = _IO.match(out.text.strip())
    if mo:
        out_name, out_type = mo.group(1), mo.group(2)
    else:
        out_name, out_type = "result", out.text.strip()
    examples = []
    for ex in a.children_of("example"):
        if "->" not in ex.text:
            raise CodegenError(ex.line, f"action の example は `入力 -> 出力` で書きます: '{ex.text}'")
        i, o = [s.strip() for s in ex.text.split("->", 1)]
        examples.append((i, o, ex.line))
    limit = retry = None
    unknown = []
    how = a.child("how")
    if how is not None:
        for h in how.children:
            if (m := _HOW_LIMIT.match(h.raw)):
                limit = m.group(1)
            elif (m := _HOW_RETRY.match(h.raw)):
                retry = int(m.group(1))
            else:
                unknown.append(h.raw)
    by = a.child("by").text.strip() if a.child("by") else "ai"
    return ActionSig(
        name=a.name, in_name=mi.group(1), in_type=go_type_of(mi.group(2), model, inp.line),
        out_name=out_name, out_type=go_type_of(out_type, model, out.line),
        examples=examples, else_=a.child("else").text.strip() if a.child("else") else "",
        nevers=[n.text for n in a.children_of("never")], by=by, limit=limit, retry=retry,
        how_unknown=unknown,
    )


def gen_actions(spec: Spec, model: Model, package: str) -> str:
    o = Out(package)
    o.w("// ErrElse — 自信がないとき、中身は必ずこれを返す（else の逃げ道に進む）。")
    o.w('var ErrElse = errors.New("else")')
    o.w()
    o.w("// How — how に書かれた決まりごと。")
    o.w("type How struct {")
    o.w("\tLimit time.Duration // limit N seconds（0 なら無制限）")
    o.w("\tRetry int           // on failure retry N times")
    o.w("}")
    o.w()
    for a in spec.decls_of("action"):
        sig = read_action(a, model)
        A = go_name(sig.name)
        o.w(f"// ---- action {sig.name} ----")
        for n in sig.nevers:
            o.w(f"// never {n}")
        o.w(f"// else {sig.else_}")
        o.w(f"// by {sig.by}")
        o.w()
        o.w(f"// {A} — 契約だけ。中身は by {sig.by} が埋める。example を全部通らないと採用されない。")
        o.w(f"type {A} interface {{")
        o.w(f"\tRun(ctx context.Context, {go_lower(sig.in_name)} {sig.in_type.go_type}) ({go_lower(sig.out_name)} {sig.out_type.go_type}, err error)")
        o.w("}")
        o.w()
        o.w(f"// {A}Impl — 中身。by ai なら AI が、by code なら自分のコードが、by connect なら外部サービスがここに入る。")
        o.w(f"var {A}Impl {A}")
        o.w()
        o.w(f"// {A}Else — 自信がないときの逃げ道（{sig.else_ or '（else 無し）'}）。")
        o.w(f"const {A}Else = {q(sig.else_)}")
        o.w()
        lim = go_duration(sig.limit) if sig.limit else "0"
        o.w(f"var {A}How = How{{Limit: {lim}, Retry: {sig.retry or 0}}}")
        for h in sig.how_unknown:
            o.w(f"// how: {h}（決まった変換が無い。AIに渡す）")
        o.w()
        o.w(f"// Run{A} は how（limit / retry）を守って中身を呼ぶ。")
        o.w(f"func Run{A}(ctx context.Context, {go_lower(sig.in_name)} {sig.in_type.go_type}) ({sig.out_type.go_type}, error) {{")
        o.w(f"\tvar zero {sig.out_type.go_type}")
        o.w(f"\tif {A}Impl == nil {{")
        o.w(f'\t\treturn zero, errors.New("{sig.name}: 中身がまだありません（by {sig.by}）")')
        o.w("\t}")
        o.w("\tvar err error")
        o.w(f"\tfor attempt := 0; attempt <= {A}How.Retry; attempt++ {{")
        o.w("\t\tc, cancel := ctx, func() {}")
        o.w(f"\t\tif {A}How.Limit > 0 {{")
        o.w(f"\t\t\tc, cancel = context.WithTimeout(ctx, {A}How.Limit)")
        o.w("\t\t}")
        o.w(f"\t\tvar out {sig.out_type.go_type}")
        o.w(f"\t\tout, err = {A}Impl.Run(c, {go_lower(sig.in_name)})")
        o.w("\t\tcancel()")
        o.w("\t\tif err == nil {")
        o.w("\t\t\treturn out, nil")
        o.w("\t\t}")
        o.w("\t\tif errors.Is(err, ErrElse) {")
        o.w("\t\t\treturn zero, err // 自信がない → 逃げ道へ。retry はしない")
        o.w("\t\t}")
        o.w("\t}")
        o.w("\treturn zero, err")
        o.w("}")
        o.w()
    return o.text()


def go_literal(value: str, f: Field, line: int) -> tuple[str, set[str]]:
    """example の値を Go の式にする。"""
    v = value.strip()
    if f.go_type == "string" or f.go_type in {go_name(t) for t in []}:
        s = v[1:-1] if v.startswith('"') and v.endswith('"') else v
        return q(s), set()
    if f.go_type == "float64":
        return v, set()
    if f.go_type == "time.Time":
        s = v[1:-1] if v.startswith('"') and v.endswith('"') else v
        return f"specTime({q(s)})", set()
    if f.go_type == "time.Duration":
        return go_duration(v), {"time"}
    # 未定義の型（Message など）は text 扱い
    s = v[1:-1] if v.startswith('"') and v.endswith('"') else v
    return f"{f.go_type}({q(s)})", set()


def gen_action_tests(spec: Spec, model: Model, package: str) -> str:
    o = Out(package)
    for a in spec.decls_of("action"):
        sig = read_action(a, model)
        A = go_name(sig.name)
        o.w(f"// Test{A} — action {sig.name} の example。誰が中身を埋めても同じ example で検証される。")
        o.w(f"func Test{A}(t *testing.T) {{")
        o.w(f"\tif {A}Impl == nil {{")
        o.w(f'\t\tt.Skip("{sig.name}: 中身がまだありません（by {sig.by}）")')
        o.w("\t}")
        o.w("\tcases := []struct {")
        o.w(f"\t\tin   {sig.in_type.go_type}")
        o.w(f"\t\twant {sig.out_type.go_type}")
        o.w("\t}{")
        for i, out, line in sig.examples:
            gi, _ = go_literal(i, sig.in_type, line)
            go_, _ = go_literal(out, sig.out_type, line)
            o.w(f"\t\t{{{gi}, {go_}}}, // L{line}")
        o.w("\t}")
        o.w("\tfor _, c := range cases {")
        o.w(f"\t\tgot, err := Run{A}(context.Background(), c.in)")
        o.w("\t\tif err != nil {")
        o.w('\t\t\tt.Errorf("%v: error %v", c.in, err)')
        o.w("\t\t\tcontinue")
        o.w("\t\t}")
        if sig.out_type.go_type == "time.Time":
            o.w("\t\tif !got.Equal(c.want) {")
        else:
            o.w("\t\tif got != c.want {")
        o.w('\t\t\tt.Errorf("%v: got %v, want %v", c.in, got, c.want)')
        o.w("\t\t}")
        o.w("\t}")
        o.w("}")
        o.w()
    return o.text()


# ---------------------------------------------------------------------------
# rule の example → テスト
# ---------------------------------------------------------------------------

_GIVEN = re.compile(r"^(\w+)\((.*)\)$")
_KV = re.compile(r'(\w+)\s+("[^"]*"|\S+)')


def gen_rule_tests(spec: Spec, model: Model, package: str) -> str:
    o = Out(package)
    o.w("// specTime は仕様の書き方の日時（\"9/24 23:59\"）を読む。年は推測しない（年 0 のまま比べる）。QUESTIONS.md Q5")
    o.w("func specTime(s string) time.Time {")
    o.w('\tfor _, layout := range []string{"1/2 15:04", "2006/1/2 15:04", "2006-01-02 15:04", "1/2"} {')
    o.w("\t\tif t, err := time.Parse(layout, s); err == nil {")
    o.w("\t\t\treturn t")
    o.w("\t\t}")
    o.w("\t}")
    o.w('\tpanic("日時が読めません: " + s)')
    o.w("}")
    o.w()
    o.w("type recorder struct{ notified []string }")
    o.w()
    o.w("func (r *recorder) Notify(rule string, item any) {")
    o.w('\tr.notified = append(r.notified, fmt.Sprintf("%s: %+v", rule, item))')
    o.w("}")
    o.w()
    for r in spec.decls_of("rule"):
        R = go_name(r.name)
        for n, ex in enumerate(r.children_of("example"), start=1):
            given = ex.children_of("given")
            at = ex.child("at")
            expects = ex.children_of("expect")
            if not expects:
                raise CodegenError(ex.line, f"rule {r.name}: example に expect がありません")
            o.w(f"// Test{R}Example{n} — rule {r.name} の example（L{ex.line}）")
            o.w(f"func Test{R}Example{n}(t *testing.T) {{")
            o.w("\ts := NewStore()")
            o.w("\tdefer s.Close()")
            o.w("\tfx := &recorder{}")
            for g in given:
                m = _GIVEN.match(g.text.strip())
                if not m or m.group(1) not in model.entities:
                    raise CodegenError(g.line, f"given は `箱名(項目 値, ...)` で書きます: '{g.text}'")
                ename = m.group(1)
                fields = {f.name: f for f in model.entities[ename]}
                parts = []
                for k, v in _KV.findall(m.group(2)):
                    if k not in fields:
                        raise CodegenError(g.line, f"given: {ename} に {k} という項目はありません")
                    lit, _ = go_literal(v, fields[k], g.line)
                    parts.append(f"{go_name(k)}: {lit}")
                o.w(f"\ts.Add{go_name(ename)}({go_name(ename)}{{{', '.join(parts)}}})")
            now = f"specTime({q(at.text.strip().strip(chr(34)))})" if at is not None else "time.Time{}"
            o.w(f"\tnow := {now}")
            when = r.child("when")
            kind = classify_when(when.text)
            if kind == "time":
                o.w(f"\tif err := Rule{R}(s, fx, now); err != nil {{")
            elif kind == "user":
                # example に user の入力が無い形は仕様に無いので、user says ルールの example は未対応
                raise CodegenError(ex.line, f"rule {r.name}: user says のルールの example の書き方が仕様にありません（QUESTIONS.md）")
            else:
                raise CodegenError(ex.line, f"rule {r.name}: この when の example はまだ変換できません")
            o.w('\t\tt.Fatalf("rule error: %v", err)')
            o.w("\t}")
            for e in expects:
                et = e.text.strip()
                m = re.match(r'^notify "(.*)"$', et)
                if not m:
                    raise CodegenError(e.line, f"expect の書き方が分かりません（決まっているのは notify \"...\"）: '{et}'")
                o.w(f"\tif !containsNotify(fx.notified, {q(m.group(1))}) {{")
                o.w(f'\t\tt.Errorf("expect notify %q, got %v", {q(m.group(1))}, fx.notified)')
                o.w("\t}")
            o.w("}")
            o.w()
    o.w("func containsNotify(list []string, want string) bool {")
    o.w("\tfor _, s := range list {")
    o.w("\t\tif strings.Contains(s, want) {")
    o.w("\t\t\treturn true")
    o.w("\t\t}")
    o.w("\t}")
    o.w("\treturn false")
    o.w("}")
    return o.text()


# ---------------------------------------------------------------------------
# 全部
# ---------------------------------------------------------------------------

def generate(spec: Spec, package: str = "hub") -> dict[str, str]:
    """ファイル名 → 中身。順序も中身も spec だけで決まる。"""
    model = build_model(spec)
    # action を先に読んで未定義の型を集める（entities.go に型宣言を出すため）
    for a in spec.decls_of("action"):
        read_action(a, model)
    files: dict[str, str] = {}
    files["entities.go"] = gen_entities(spec, model, package)
    files["flows.go"] = gen_flows(spec, model, package)
    files["lists.go"] = gen_lists(spec, model, package)
    files["matches.go"] = gen_matches(spec, model, package)
    files["rules.go"] = gen_rules(spec, model, package)
    files["actions.go"] = gen_actions(spec, model, package)
    files["actions_test.go"] = gen_action_tests(spec, model, package)
    files["rules_test.go"] = gen_rule_tests(spec, model, package)
    files["go.mod"] = f"module {package}\n\ngo 1.22\n"
    return files


def generate_to_dir(spec: Spec, out_dir: str, package: str = "hub") -> list[str]:
    files = generate(spec, package)
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for name in sorted(files):
        p = os.path.join(out_dir, name)
        with open(p, "w", encoding="utf-8") as f:
            f.write(files[name])
        written.append(p)
    return written
